#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080

mkdir -p $OPENSHIFT_DATA_DIR/m2/repository
echo -e "<settings><localRepository>$OPENSHIFT_DATA_DIR/m2/repository</localRepository>\n</settings>\n" > $OPENSHIFT_DATA_DIR/settings.xml
cd $OPENSHIFT_REPO_DIR


# nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_DIY_IP $OPENSHIFT_REPO_DIR/diy |& /usr/bin/logshifter -tag diy &
nohup mvn -s $OPENSHIFT_DATA_DIR/settings.xml clean install
cd techSupport-web
nohup mvn -s $OPENSHIFT_DATA_DIR/settings.xml jetty:run &

